name: Laravel

on:
  push:
    branches: 
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - name: Install Docker
      run: docker-compose up -d --build
    - name: Install Dependencies
      run: docker exec -it laravel-deploy_php-fpm_1 composer install
    - name: Up Containers
      run: |
        docker start laravel-deploy_redis_1
        docker start laravel-deploy_php-fpm_1
        docker start laravel-deploy_webserver_1
    - name: Configure Application
      run: |
        docker exec -it laravel-deploy_php-fpm_1 php artisan key:generate
        docker exec -it laravel-deploy_php-fpm_1 php artisan cache:clear
        docker exec -it laravel-deploy_php-fpm_1 php artisan config:clear
        docker exec -it laravel-deploy_php-fpm_1 php artisan config:cache
        docker exec -it laravel-deploy_php-fpm_1 php artisan storage:link      
    - name: Directory Permissions
      run: docker exec -it laravel-deploy_php-fpm_1 chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        docker exec -it laravel-deploy_php-fpm_1 mkdir -p database
        docker exec -it laravel-deploy_php-fpm_1 touch database/database.sqlite
    #- name: Execute tests (Unit and Feature tests) via PHPUnit
    #  env:
    #    DB_CONNECTION: sqlite
    #    DB_DATABASE: database/database.sqlite
    #  run: vendor/bin/phpunit
